### PR TITLE
fix: add exclude field in vite config

### LINKED ISSUE #40: e2e test failing on running the npm run test
Hello, I run `npm run test` in the web directory

# Output: 
image

# Expected:
image

# How to regenerate the error:
Run `npm run test` in the web directory

# Explanation: 
The `npm run test` is supposed to run only `vitest` according to the package.json scripts
But as you can see in the output that is running the tests in the `e2e/` directory (playwright tests), 
which is why it is failing

# Workaround: 
Add a exclude field in the vite object in `web/svelte.config.js` file, this will stop vite from running tests in `e2e/`.

### PR DESCRIPTION
**Pull request by rajatgupta24**
- This PR add a exclude file in the `web/svelte.config.js` file, this will prevent vite from running playwright tests.
- This also delete files that are not being used.
	- web/hooks/laravelSanctum.ts
	- web/src/hooks.ts
fixes #40

Signed-off-by: rajatgupta24 <rajat2411gupta@gmail.com>

### CODE REVIEW

File: web/src/routes/admin/pipelines/index.svelte [hunk 1]
```diff
@@ -41,7 +41,10 @@
         headerName: 'Build',
         field: 'build',
         cellRenderer: (params) => {
-          return HTMLInColumnCell(`/pipelines/${params.data.gitOwner}/${params.data.gitRepository}/${params.data.gitBranch}/${params.data.build}`, params.data.build)
+          return HTMLInColumnCell(
```
Comment (ankitm123) [inline web/src/routes/admin/pipelines/index.svelte:44]: Is this after linting?

Comment (rajatgupta24) [reply web/src/routes/admin/pipelines/index.svelte:44]: Yes

**Review by ankitm123 — APPROVED** [review]
